version: '3.8'
services:
  flasky:
    build: .
    ports:
      - "8000:5000"
    environment:
      FLASK_CONFIG: development
      FLASKY_ADMIN: admin@example.com
    volumes:
      - .:/app
    restart: always
