"""Initial migration

Revision ID: 23b4edd84440
Revises: 51f5ccfba190
Create Date: 2025-09-18 21:11:55.059305

"""

# revision identifiers, used by Alembic.
revision = '23b4edd84440'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
